/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package blessingvisual;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Toolkit;
import javax.swing.JDialog;

/**
 *
 * @author Kamisato Ayaka
 */
public class DialogInfo extends javax.swing.JDialog {

    /**
     * Creates new form DialogInfo
     */
    static int x=0;
    static String msg="Apakah Kamu Yakin?";
    static String title="Info";
    static boolean isMsg =false;
    
    public DialogInfo(Frame parent, boolean modal,String msg,String title,boolean isMsg) {
        super(parent, modal);
        this.msg=msg;
        this.title=title;
        this.isMsg = isMsg;
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        if (isMsg) {
            btnTidak.setVisible(false);
            btnYa.setBackground(Color.white);
            btnYa.setForeground(view.Primary);
            btnYa.setText("Tutup");
            btnYa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(50, 79, 83)));
        }
        lb.setText(msg);
    }
    
    public DialogInfo(JDialog parent, boolean modal, String msg,String title,boolean isMsg) {
        super(parent, modal);
        this.msg=msg;
        this.title=title;
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        if (isMsg) {
            btnTidak.setVisible(false);
            btnYa.setBackground(Color.white);
            btnYa.setForeground(view.Primary);
            btnYa.setText("Tutup");
            btnYa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(50, 79, 83)));
        }
        lb.setText(msg);
    }
    
    public static int showPrompt(Frame parent,boolean modal,String msg,String title,boolean isMsg){
        new DialogInfo(parent, modal,msg,title,isMsg).show();
        return x;
    }
    
    public static void showMsg(Frame parent,boolean modal,String msg,String title,boolean isMsg){
        new DialogInfo(parent, modal,msg,title,isMsg).show();
    }
    
    public static void showMsg(JDialog parent,boolean modal,String msg,String title,boolean isMsg){
        new DialogInfo(parent, modal,msg,title,isMsg).show();
    }
    

    public static  int showPrompt(JDialog parent,boolean modal,String msg,String title,boolean isMsg){
        new DialogInfo(parent, modal,msg,title,isMsg).show();
        return x;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnYa = new javax.swing.JButton();
        btnTidak = new javax.swing.JButton();
        lb = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 200));
        setMinimumSize(new java.awt.Dimension(400, 200));
        setName("dialogInfo"); // NOI18N
        setPreferredSize(new java.awt.Dimension(400, 200));
        setResizable(false);
        setSize(new java.awt.Dimension(400, 200));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(459, 324));

        btnYa.setBackground(new java.awt.Color(50, 79, 83));
        btnYa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnYa.setForeground(new java.awt.Color(255, 255, 255));
        btnYa.setText("Ya");
        btnYa.setBorder(null);
        btnYa.setFocusPainted(false);
        btnYa.setMaximumSize(new java.awt.Dimension(30, 120));
        btnYa.setMinimumSize(new java.awt.Dimension(30, 120));
        btnYa.setPreferredSize(new java.awt.Dimension(30, 120));
        btnYa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYaActionPerformed(evt);
            }
        });

        btnTidak.setBackground(new java.awt.Color(255, 255, 255));
        btnTidak.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTidak.setForeground(new java.awt.Color(50, 79, 83));
        btnTidak.setText("Tidak");
        btnTidak.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(50, 79, 83)));
        btnTidak.setFocusPainted(false);
        btnTidak.setMaximumSize(new java.awt.Dimension(30, 120));
        btnTidak.setMinimumSize(new java.awt.Dimension(30, 120));
        btnTidak.setPreferredSize(new java.awt.Dimension(30, 120));
        btnTidak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTidakActionPerformed(evt);
            }
        });

        lb.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        lb.setForeground(new java.awt.Color(50, 79, 83));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lb, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnTidak, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnYa, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lb, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnYa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTidak, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnYaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYaActionPerformed
        x=1;
        dispose();
    }//GEN-LAST:event_btnYaActionPerformed

    private void btnTidakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTidakActionPerformed
        x=0;
        dispose();
    }//GEN-LAST:event_btnTidakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogInfo dialog = new DialogInfo(new javax.swing.JFrame(), true,msg,title,isMsg);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTidak;
    private javax.swing.JButton btnYa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb;
    // End of variables declaration//GEN-END:variables
}
